{"name": "Login sem senha retorna erro e mensagem", "status": "failed", "statusDetails": {"message": "AssertionError: Esperado um de [400, 403], obtido 401\n", "trace": "  File \"C:\\Users\\leanc\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\leanc\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\api_steps.py\", line 38, in step_status_one_of\n    assert got in expected, f\"Esperado um de {sorted(expected)}, obtido {got}\"\n           ^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given the API base url", "status": "passed", "start": 1757525470221, "stop": 1757525470222}, {"name": "Given the request body", "status": "passed", "attachments": [{"name": ".text", "source": "499455cf-a5f7-42b7-8cdd-08050118f6c4-attachment.txt", "type": "text/plain"}], "start": 1757525470222, "stop": 1757525470223}, {"name": "When I send a POST request to \"/api/login\"", "status": "passed", "start": 1757525470223, "stop": 1757525470538}, {"name": "Then the response status code should be one of 400,403", "status": "failed", "statusDetails": {"message": "AssertionError: Esperado um de [400, 403], obtido 401\n", "trace": "  File \"C:\\Users\\leanc\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\leanc\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\api_steps.py\", line 38, in step_status_one_of\n    assert got in expected, f\"Esperado um de {sorted(expected)}, obtido {got}\"\n           ^^^^^^^^^^^^^^^\n"}, "start": 1757525470538, "stop": 1757525470539}, {"name": "And the response should contain text \"error\"", "status": "skipped", "start": 1757525470540, "stop": 1757525470540}], "start": 1757525470220, "stop": 1757525470540, "uuid": "a6a77c37-7cf3-4d83-b6b6-f8f717306879", "historyId": "330691fbb7a7645e64ebb381e3e19245", "fullName": "Casos negativos: Login sem senha retorna erro e mensagem", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "auth"}, {"name": "tag", "value": "negative"}, {"name": "feature", "value": "Casos negativos"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}